### ISSUE TITLE
Node health monitoring and reporting

### ISSUE THREAD

**Issue by Seth-Schmidt** [PowerLoom/snapshotter-lite#13]
**Is your feature request related to a problem?**
The snapshotter-lite nodes currently require manual monitoring to discover any issues with the node.

**Describe the solution you'd like**
snapshotter-lite should keep an internal health state and report any issues to operators (using Telegram).

**Describe alternatives you've considered**
An alternative service could be used for reporting, such as Discord.

**Additional context**
None

**Comment by kanikamishra** [comment]
Tested the Lite node and checked:
Not getting any error messages on TelegramSnapshotterReportingBot channel on my Telegram.

Things I tried to get error:
- Abruptly stopping the node
- Wrong RPC in .env

Things which we should mention in Docs:
- How to get telegram ID as its nowhere mention which ID we are talking about here.
- User has to join PowerloomReportingBot channel and click Start to get this ID and has to mention it in .env

Issues with Logs:
Its pings /health end point and gives 200 even when node is not properly running

![Image](https://github.com/PowerLoom/snapshotter-lite/assets/8338694/df3fbf05-d51c-4879-ab90-38ab395af1b1)

**Comment by Seth-Schmidt** [comment]
On the lack of error messages:

> - Abruptly stopping the node

This will not send a message since the monitoring is happening inside the node itself. Stopping all processes would prevent the node from sending any messages. https://github.com/PowerLoom/snapshotter-lite/issues/24 will cover cases where a node is unintentionally stopped and needs to be restarted.

> - Wrong RPC in .env

If an incorrect RPC is provided, then the node will fail to pass the initial startup checks. One of these checks is to process a dummy event, and if that fails, the node will display a message to the user before shutting down. Neither the powerloom reporting endpoint or the tg reporting service will receive a message in this case since this would fall under setup, and the user will already be at their computer to address the issue.


Can you provide a bit more detail on the logging issue? I see that the node is setup correctly in the screenshot, so it shouldn't be reporting any errors.

**Comment by anomit** [comment]
> Its pings /health end point and gives 200 even when node is not properly running

This needs a  separate review, discussion and issue to track the implementation and importance of the `/health` endpoint. It has been discussed in passing earlier to ensure this request handler checks other datapoints, status datasets stored in redis to determine the condition of the node as well as bringing down the top level docker compose setup down.

**Comment by anomit** [comment]
Can confirm the test script included included here sends a telegram alert 
<img width="547" alt="Screenshot 2024-04-23 at 1 50 27 PM" src="https://github.com/PowerLoom/snapshotter-lite/assets/101592/d71e5916-b502-4d00-af53-a05d81c14b8a">

**Comment by anomit** [comment]
<img width="702" alt="Screenshot 2024-04-23 at 2 01 15 PM" src="https://github.com/PowerLoom/snapshotter-lite/assets/101592/ce142669-155b-4bff-8b86-78110874e067">

Also tested with rate limits. Alerts are being received.

**Comment by anomit** [comment]
Also tested with rate limits. Alerts are being received.
![Uploading Screenshot 2024-04-23 at 2.01.15 PM.png…]()

**Comment by anomit** [comment]
Also tested with rate limits. Alerts are being received.
<img width="702" alt="Screenshot 2024-04-23 at 2 01 15 PM" src="https://github.com/PowerLoom/snapshotter-lite/assets/101592/234e9724-b620-4f7d-9953-76fb411408c4">

**Comment by anomit** [comment]
This is completed as part of PR #20
