### ISSUE TITLE
Add docker restart to snappshotter lite

### ISSUE THREAD

**Issue by halfdoctor** [PowerLoom/snapshotter-lite#24]
**Is your feature request related to a problem?**
Some of us use docker to run the node.
When power recycles (some of us live in countries where the outages/cuts are more regular than the sunshine) node doesn't function.
Until you go and see the dashboard/logs.

**Describe the solution you'd like**
When power recycles node restarts.

**Additional context**
Possible fix, (it works)
[docker-compose.yaml](https://github.com/halfdoctor/snapshotter-lite/blob/main/docker-compose.yaml)
`version: '3.9'

services:
  snapshotter-lite:
    image: ghcr.io/powerloom/snapshotter-lite:${IMAGE_TAG}
    volumes:
      - ./logs:/logs
    environment:
      - SIGNER_ACCOUNT_ADDRESS=$SIGNER_ACCOUNT_ADDRESS
      - SIGNER_ACCOUNT_PRIVATE_KEY=$SIGNER_ACCOUNT_PRIVATE_KEY
      - SLOT_ID=$SLOT_ID
      - RELAYER_HOST=$RELAYER_HOST
      - SOURCE_RPC_URL=$SOURCE_RPC_URL
      - PROST_RPC_URL=$PROST_RPC_URL
      - IPFS_URL=$IPFS_URL
      - IPFS_API_KEY=$IPFS_API_KEY
      - IPFS_API_SECRET=$IPFS_API_SECRET
      - PROTOCOL_STATE_CONTRACT=$PROTOCOL_STATE_CONTRACT
      - SLACK_REPORTING_URL=$SLACK_REPORTING_URL
      - POWERLOOM_REPORTING_URL=$POWERLOOM_REPORTING_URL
      - WEB3_STORAGE_TOKEN=$WEB3_STORAGE_TOKEN
      - NAMESPACE=$NAMESPACE
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    command:
      bash -c "sh snapshotter_autofill.sh && sh init_docker.sh"
    restart: unless-stopped
  ipfs:
    image: ipfs/kubo:release
    profiles: ["ipfs"]
    environment:
      - IPFS_PROFILE=server
    entrypoint: >
      /bin/sh -c "
      echo 'adding cronjob';
      mkdir -p /var/spool/cron/crontabs;
      croncmd=\"cd /data/ipfs && find . -type f -mtime +7 -name \\"*.data\\" | xargs rm -f 2>&1\";
      cronjob=\"0 * * * * $$croncmd\";
      ( crontab -l | grep -v -F \"$$croncmd\" ; echo \"$$cronjob\" ) | crontab -;
      echo 'starting ipfs';
      /sbin/tini -- /usr/local/bin/start_ipfs daemon --migrate=true --agent-version-suffix=docker;
      "
    #command:
    #   ["daemon", "--migrate=true", "--agent-version-suffix=docker"]
    restart: on-failure
`

**Comment by anomit** [comment]
Instructions to be added in README and troubleshooting/monitoring section of docs

**Comment by anomit** [comment]
Also to be reviewed: multi node setup enhancement to support CLI arguments.

**Comment by xadahiya** [comment]
Moving to current iteration.
